// Generated by gencpp from file task2/hello.msg
// DO NOT EDIT!


#ifndef TASK2_MESSAGE_HELLO_H
#define TASK2_MESSAGE_HELLO_H

#include <ros/service_traits.h>


#include <task2/helloRequest.h>
#include <task2/helloResponse.h>


namespace task2
{

struct hello
{

typedef helloRequest Request;
typedef helloResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct hello
} // namespace task2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task2::hello > {
  static const char* value()
  {
    return "1d267952d5d13e898b2e45c1c34041f3";
  }

  static const char* value(const ::task2::hello&) { return value(); }
};

template<>
struct DataType< ::task2::hello > {
  static const char* value()
  {
    return "task2/hello";
  }

  static const char* value(const ::task2::hello&) { return value(); }
};


// service_traits::MD5Sum< ::task2::helloRequest> should match
// service_traits::MD5Sum< ::task2::hello >
template<>
struct MD5Sum< ::task2::helloRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task2::hello >::value();
  }
  static const char* value(const ::task2::helloRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task2::helloRequest> should match
// service_traits::DataType< ::task2::hello >
template<>
struct DataType< ::task2::helloRequest>
{
  static const char* value()
  {
    return DataType< ::task2::hello >::value();
  }
  static const char* value(const ::task2::helloRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task2::helloResponse> should match
// service_traits::MD5Sum< ::task2::hello >
template<>
struct MD5Sum< ::task2::helloResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task2::hello >::value();
  }
  static const char* value(const ::task2::helloResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task2::helloResponse> should match
// service_traits::DataType< ::task2::hello >
template<>
struct DataType< ::task2::helloResponse>
{
  static const char* value()
  {
    return DataType< ::task2::hello >::value();
  }
  static const char* value(const ::task2::helloResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK2_MESSAGE_HELLO_H
